'use strict';

const path = require('path');
const fs   = require('fs');

// config.json is generated by the prebuild script from .env and bundled into
// the asar — readable by fs inside the archive at __dirname.
const config = JSON.parse(fs.readFileSync(path.join(__dirname, 'config.json'), 'utf8'));

const { app, BrowserWindow, Tray, Menu, screen, nativeImage, ipcMain } = require('electron');

const WIDGET_W = 320;
const WIDGET_H = 480;

// Deferred — app.getPath() must not be called until after app is ready
function posFile() {
  return path.join(app.getPath('userData'), 'window-position.json');
}

function userConfigPath() {
  return path.join(app.getPath('userData'), 'user-config.json');
}

function loadUserConfig() {
  try {
    const raw = fs.readFileSync(userConfigPath(), 'utf8');
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

ipcMain.handle('config:load', () => loadUserConfig());

ipcMain.handle('config:save', (_e, overrides) => {
  // Validate: only accept known keys with correct types
  const clean = {};
  if (typeof overrides.readToken === 'string') clean.readToken = overrides.readToken.trim();
  if (typeof overrides.refreshMs === 'number' && overrides.refreshMs >= 60000) {
    clean.refreshMs = overrides.refreshMs;
  }
  try {
    fs.writeFileSync(userConfigPath(), JSON.stringify(clean, null, 2), 'utf8');
    log(`Saved user config: ${JSON.stringify(clean)}`);
    return { ok: true };
  } catch (err) {
    log(`Failed to save user config: ${err.message}`);
    return { ok: false, error: err.message };
  }
});

let win;
let tray;

// Enforce single instance — second launch focuses the existing window and exits
const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
} else {
  app.on('second-instance', () => {
    if (win) {
      if (!win.isVisible()) win.show();
      win.focus();
    }
  });
}

function log(...args) {
  const ts = new Date().toISOString();
  const line = `[${ts}] [main] ${args.join(' ')}`;
  console.log(line);
}

function loadSavedPosition() {
  try {
    const raw = fs.readFileSync(posFile(), 'utf8');
    const pos = JSON.parse(raw);
    if (typeof pos.x === 'number' && typeof pos.y === 'number') {
      log(`Restored window position x=${pos.x} y=${pos.y}`);
      return pos;
    }
  } catch {
    // no saved position yet — fall through to default
  }
  return null;
}

function savePosition() {
  if (!win || win.isDestroyed()) return;
  const [x, y] = win.getPosition();
  try {
    fs.writeFileSync(posFile(), JSON.stringify({ x, y }), 'utf8');
    log(`Saved window position x=${x} y=${y}`);
  } catch (err) {
    log(`Failed to save position: ${err.message}`);
  }
}

function getDefaultPosition() {
  const { width, height } = screen.getPrimaryDisplay().workAreaSize;
  return {
    x: width  - WIDGET_W - 16,
    y: height - WIDGET_H - 16,
  };
}

function createWindow() {
  const pos = loadSavedPosition() || getDefaultPosition();
  log(`Creating window at x=${pos.x} y=${pos.y}`);

  win = new BrowserWindow({
    width:       WIDGET_W,
    height:      WIDGET_H,
    x:           pos.x,
    y:           pos.y,
    frame:       false,
    resizable:   false,
    alwaysOnTop: true,
    skipTaskbar: true,
    transparent: true,
    show:        false,
    webPreferences: {
      preload:             path.join(__dirname, 'preload.js'),
      contextIsolation:    true,
      nodeIntegration:     false,
      additionalArguments: [
        `--server-url=${config.SERVER_URL}`,
        `--read-token=${config.READ_TOKEN || ''}`,
      ],
    },
  });

  win.loadFile(path.join(__dirname, 'renderer.html'));
  log(`Loading renderer from ${path.join(__dirname, 'renderer.html')}`);
  log(`SERVER_URL = ${config.SERVER_URL}`);

  // Forward renderer console messages to the main-process terminal
  win.webContents.on('console-message', (_e, level, message, line, sourceId) => {
    const lvl = ['verbose', 'info', 'warn', 'error'][level] ?? 'info';
    console.log(`[renderer:${lvl}] ${message}  (${sourceId}:${line})`);
  });

  win.webContents.on('did-fail-load', (_e, errorCode, errorDesc, url) => {
    log(`did-fail-load  url=${url}  code=${errorCode}  desc=${errorDesc}`);
  });

  win.webContents.on('did-finish-load', () => {
    log('did-finish-load -- renderer HTML loaded OK');
  });

  // Show the window once the page has loaded
  win.once('ready-to-show', () => {
    log('ready-to-show -- showing window');
    win.show();
  });

  // Save position whenever the window is moved
  win.on('moved', savePosition);
}

function createTray() {
  const iconPath = path.join(__dirname, 'tray-icon.png');
  log(`Loading tray icon from ${iconPath}`);
  const icon = nativeImage.createFromPath(iconPath);
  if (icon.isEmpty()) log('WARNING: tray icon is empty — check tray-icon.png');
  tray = new Tray(icon);
  tray.setToolTip('nextUp Calendar');

  tray.on('click', () => {
    if (!win) return;
    if (win.isVisible()) {
      log('Tray click — hiding window');
      win.hide();
    } else {
      log('Tray click — showing window');
      win.show();
      win.focus();
      // Trigger a data refresh each time the widget is shown
      win.webContents.send('ipc:do-refresh');
    }
  });

  const contextMenu = Menu.buildFromTemplate([
    {
      label: 'Refresh',
      click: () => {
        if (win && win.isVisible()) win.webContents.send('ipc:do-refresh');
      },
    },
    { type: 'separator' },
    { label: 'Exit', click: () => { savePosition(); app.quit(); } },
  ]);

  tray.on('right-click', () => tray.popUpContextMenu(contextMenu));
}

app.whenReady().then(() => {
  log(`App ready — userData=${app.getPath('userData')}`);
  createWindow();
  createTray();
});

app.on('before-quit', () => {
  savePosition();
});

app.on('window-all-closed', () => {
  // Do not quit — app lives in the system tray
});
